/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hello.world;

public class AppTest {
    //    @Test
    public void testAppHasAGreeting() {
        App classUnderTest = new App();
//        assertNotNull("app should have a greeting", "app should have a greeting");
    }
}
